/*
 * Add Copyright
 */
package com.amiyul.phantom.driver;

import com.amiyul.phantom.api.logging.LoggerUtils;

/**
 * Base class for tasks that notify a listener of the values generated by the task after completion.
 */
public abstract class BaseNotifyingTask<T> extends BaseTask<T> {
	
	private Listener<T> listener;
	
	public BaseNotifyingTask(String name, Listener<T> listener) {
		super(name);
		this.listener = listener;
	}
	
	@Override
	T doExecute() {
		T result = null;
		
		try {
			result = getResult();
			if (listener != null) {
				LoggerUtils.debug("Completed successfully, notifying listener -> " + listener);
				
				try {
					listener.onSuccess(result);
				}
				catch (Throwable t) {
					LoggerUtils.error("An error occurred while notifying listener", t);
				}
			}
		}
		catch (Throwable throwable) {
			LoggerUtils.debug("Completed with errors, notifying listener -> " + listener);
			
			if (listener != null) {
				try {
					listener.onFailure(throwable);
				}
				catch (Throwable t) {
					LoggerUtils.error("An error occurred while notifying listener after a failure", t);
				}
			}
		}
		
		return result;
	}
	
	/**
	 * Gets the result
	 *
	 * @return T the result
	 * @throws Exception
	 */
	public abstract T getResult() throws Exception;
	
}
