/*
 * Add Copyright
 */
package com.amiyul.phantom.driver;

/**
 * This interface should be implemented by a named runnable or callable task that generates a value
 * when executed, the task name will be used as the thread name.
 * 
 * @param <T> type of the result generated by the task when executed
 */
public interface Task<T> {
	
	/**
	 * Gets the task name
	 * 
	 * @return the task name
	 */
	String getName();
	
	/**
	 * Executes the task to generate a result
	 *
	 * @return T the result
	 */
	T execute();
	
}
