#
# Copyright (C) Amiyul LLC - All Rights Reserved
#
# This source code is protected under international copyright law. All rights
# reserved and protected by the copyright holder.
#
# This file is confidential and only available to authorized individuals with the
# permission of the copyright holder. If you encounter this file and do not have
# permission, please contact the copyright holder and delete this file.
#

version: "3.3"

services:
  phantom-prod:
    image: mysql:5.7.40
    container_name: prod
    env_file:
      - prod.env
    ports:
      - "3506:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./initial-data-prod.sql:/docker-entrypoint-initdb.d/initial-data.sql

  phantom-research:
    image: mysql:5.7.40
    container_name: research
    env_file:
      - research.env
    ports:
      - "3606:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./initial-data-research.sql:/docker-entrypoint-initdb.d/initial-data.sql
